[package]
name = "n3gb-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22"
geo-types = "0.7"
proj = "0.31.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
